### ISSUE TITLE
Context is lengthy and Im wondering if it is needed

### ISSUE THREAD

**Issue by vongohren** [awoie/rwot11-the-hague#5]
Right now context is quite lengthy and wonder if we need all this to build a background for why holder binding is needed?

https://github.com/awoie/rwot11-the-hague/blob/master/draft-documents/verfiable-credentials-holder-binding.md#context

Are there no pre text we can refer to so that we expect pre knowledge before someone reads this?
As context is basically defining what issuance, verification and holding is, and touch upon the binding part in some of the text

**Comment by ntn-x2** [comment]
+1 for this. It might make sense to collapse it into the problem section.

**Comment by RieksJ** [comment]
We need the context description because holder binding (did we already define what it is, and what it is not?) is a very ambiguous term. Only if you have a solid foundation can you hope to explain what (we argue that) it means. Our audience typically does not have such a foundation, so we must describe it. I don't know of any pretext that we can refer to (and that we can expect readers to read). If you feel strongly about this, we might transfer the lengthy text to an Appendix, summarize the key points in the body of the text and refer to the appendix.

**Comment by vongohren** [comment]
I feel this is covered and under discussion on the paper: https://docs.google.com/document/d/1_5eXdxsJ3dDMzdmVTkHi0p-PttI1Wa0RPErC9EJ-0SU/edit# So closing this issue
